/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "eu-west-2",
//     "aws_appsync_graphqlEndpoint": "https://4yjankodafconpf3mrimlp5v3m.appsync-api.eu-west-2.amazonaws.com/graphql",
//     "aws_appsync_region": "eu-west-2",
//     "aws_appsync_authenticationType": "API_KEY",
//     "aws_appsync_apiKey": "da2-crqkls77tbhirih64edd6n74oq"
// };

// export default awsmobile;

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://4yjankodafconpf3mrimlp5v3m.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-crqkls77tbhirih64edd6n74oq",
    "aws_cognito_identity_pool_id": "eu-west-2:f0c01928-2b7f-4746-a5cc-8aa6199a836f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_3nbjmOOXl",
    "aws_user_pools_web_client_id": "4hhu5pqhq0nn52r8d4qqjg1ddm",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
